# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DVFYT.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(395, 560)
        MainWindow.setMinimumSize(QtCore.QSize(395, 560))
        MainWindow.setMaximumSize(QtCore.QSize(395, 560))
        MainWindow.setBaseSize(QtCore.QSize(395, 560))
        font = QtGui.QFont()
        font.setFamily("Candara")
        font.setPointSize(9)
        MainWindow.setFont(font)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        MainWindow.setMouseTracking(True)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("QPushButton{\n"
"border:1px solid #b60423;\n"
"border-radius:10px;\n"
"color:white;\n"
"background-color:#1b1b1b;\n"
"}\n"
"QPushButton:hover{\n"
"border:1px solid #d3062a;\n"
"background-color:#202020;\n"
"}\n"
"QPushButton:pressed{\n"
"background-color:0d0d0d;\n"
"border:1px solid #a1031f;\n"
"color:#d7d6d6;\n"
"}\n"
"QMainWindow{background-color:#1b1b1b;}")
        MainWindow.setIconSize(QtCore.QSize(32, 32))
        MainWindow.setDockNestingEnabled(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem)
        self.infoblock = QtWidgets.QPlainTextEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Candara Light")
        font.setPointSize(16)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.infoblock.setFont(font)
        self.infoblock.setMouseTracking(False)
        self.infoblock.setStyleSheet("QPlainTextEdit{\n"
"background-color:#1b1b1b;\n"
"border:2px solid #b60423;\n"
"border-radius:5px;\n"
"color:white;}")
        self.infoblock.setPlainText("")
        self.infoblock.setObjectName("infoblock")
        self.verticalLayout.addWidget(self.infoblock)
        spacerItem1 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem1)
        self.linkspace = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.linkspace.sizePolicy().hasHeightForWidth())
        self.linkspace.setSizePolicy(sizePolicy)
        self.linkspace.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily("Candara")
        font.setPointSize(10)
        self.linkspace.setFont(font)
        self.linkspace.setStyleSheet("QLineEdit{\n"
"border:2px solid #b60423;\n"
"border-radius:5px;\n"
"color:white;\n"
"background-color:#1b1b1b;}")
        self.linkspace.setText("")
        self.linkspace.setObjectName("linkspace")
        self.verticalLayout.addWidget(self.linkspace)
        spacerItem2 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem2)
        self.Button_1 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Button_1.sizePolicy().hasHeightForWidth())
        self.Button_1.setSizePolicy(sizePolicy)
        self.Button_1.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("Candara")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.Button_1.setFont(font)
        self.Button_1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Button_1.setStyleSheet("QPushButton{\n"
"border:3px solid #b60423;\n"
"border-radius:10px;\n"
"color:white;\n"
"background-color:#1b1b1b;\n"
"}\n"
"QPushButton:hover{\n"
"border:3px solid #d3062a;\n"
"background-color:#202020;\n"
"}\n"
"QPushButton:pressed{\n"
"background-color:0d0d0d;\n"
"border:3px solid #a1031f;\n"
"color:#d7d6d6;\n"
"}")
        self.Button_1.setObjectName("Button_1")
        self.verticalLayout.addWidget(self.Button_1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem3)
        self.Button_2 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Button_2.sizePolicy().hasHeightForWidth())
        self.Button_2.setSizePolicy(sizePolicy)
        self.Button_2.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("Candara")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.Button_2.setFont(font)
        self.Button_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Button_2.setStyleSheet("QPushButton{\n"
"border:3px solid #b60423;\n"
"border-radius:10px;\n"
"color:white;\n"
"background-color:#1b1b1b;\n"
"}\n"
"QPushButton:hover{\n"
"border:3px solid #d3062a;\n"
"background-color:#202020;\n"
"}\n"
"QPushButton:pressed{\n"
"background-color:0d0d0d;\n"
"border:3px solid #a1031f;\n"
"color:#d7d6d6;\n"
"}")
        self.Button_2.setObjectName("Button_2")
        self.verticalLayout.addWidget(self.Button_2)
        spacerItem4 = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem4)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
        self.infoblock.setReadOnly(True)
        self.linkspace.setPlaceholderText("Вставьте ссылку на видео")
        
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Установщик видео с YouTube"))
        self.Button_1.setText(_translate("MainWindow", "Скачать видео"))
        self.Button_2.setText(_translate("MainWindow", "Выбрать папку для сохранения видео"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
